# Generated by Django 4.2.6 on 2023-10-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=15)),
                ('first_visit', models.DateTimeField()),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('visit_number', models.IntegerField(default=1)),
            ],
        ),
    ]
