# Generated by Django 4.2.6 on 2023-10-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
