# Generated by Django 4.2.6 on 2023-10-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='first_visit',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
