# Generated by Django 4.2.6 on 2023-10-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_alter_visitor_first_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='country_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='tz_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
