# Generated by Django 4.2.6 on 2023-10-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_alter_useraccount_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user_name',
            new_name='username',
        ),
    ]
