# Generated by Django 4.2.6 on 2023-10-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_useraccount_is_active_useraccount_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='email_adress',
            new_name='email',
        ),
    ]
